eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ribbon-consumer
  mvc:
    view:
      prefix: /
      suffix: .jsp
  
 
server:
  port: 8010



  